apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-depl
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: posts
  template:
    metadata:
       labels:
        app: posts
    spec:
      containers:
        - name: post
          image: shuhaibzahir/posts
---
apiVersion: v1
kind: Service
metadata:
  name: post-cluster-srv
spec:
  selector:
    app: posts
  ports:
    - name: posts-srv
      protocol: TCP
      port: 5050
      targetPort: 5050
---
apiVersion: v1
kind: Service
metadata:
  name: post-node-srv
spec:
  type: NodePort
  selector:
    app: posts
  ports:
    - name: posts
      protocol: TCP
      port: 5050 
      targetPort: 5050
